package com.zenixia.plugins.hexiagon.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.zenixia.plugins.hexiagon.model.Announcement;
import com.zenixia.plugins.hexiagon.service.AnnouncementLocalServiceUtil;

/**
 * The extended model base implementation for the Announcement service. Represents a row in the &quot;Hexiagon_Announcement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnnouncementImpl}.
 * </p>
 *
 * @author guillaumelenoir
 * @see AnnouncementImpl
 * @see com.zenixia.plugins.hexiagon.model.Announcement
 * @generated
 */
public abstract class AnnouncementBaseImpl extends AnnouncementModelImpl
    implements Announcement {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a announcement model instance should use the {@link Announcement} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AnnouncementLocalServiceUtil.addAnnouncement(this);
        } else {
            AnnouncementLocalServiceUtil.updateAnnouncement(this);
        }
    }
}
