package com.zenixia.plugins.hexiagon.model.impl;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.zenixia.plugins.hexiagon.model.Announcement;
import com.zenixia.plugins.hexiagon.model.AnnouncementModel;
import com.zenixia.plugins.hexiagon.model.AnnouncementSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * The base model implementation for the Announcement service. Represents a row in the &quot;Hexiagon_Announcement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.zenixia.plugins.hexiagon.model.AnnouncementModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnnouncementImpl}.
 * </p>
 *
 * @author guillaumelenoir
 * @see AnnouncementImpl
 * @see com.zenixia.plugins.hexiagon.model.Announcement
 * @see com.zenixia.plugins.hexiagon.model.AnnouncementModel
 * @generated
 */
@JSON(strict = true)
public class AnnouncementModelImpl extends BaseModelImpl<Announcement>
    implements AnnouncementModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a announcement model instance should use the {@link com.zenixia.plugins.hexiagon.model.Announcement} interface instead.
     */
    public static final String TABLE_NAME = "Hexiagon_Announcement";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "announcementId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "typeId", Types.BIGINT },
            { "folderId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "currencyId", Types.BIGINT },
            { "title", Types.VARCHAR },
            { "emailAddress", Types.VARCHAR },
            { "phoneNumber", Types.VARCHAR },
            { "price", Types.BIGINT },
            { "content", Types.VARCHAR },
            { "status", Types.INTEGER },
            { "statusByUserId", Types.BIGINT },
            { "statusByUserName", Types.VARCHAR },
            { "statusDate", Types.TIMESTAMP },
            { "countryId", Types.BIGINT },
            { "regionId", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table Hexiagon_Announcement (uuid_ VARCHAR(75) null,announcementId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,typeId LONG,folderId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,currencyId LONG,title STRING null,emailAddress VARCHAR(75) null,phoneNumber VARCHAR(75) null,price LONG,content STRING null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,countryId LONG,regionId LONG)";
    public static final String TABLE_SQL_DROP = "drop table Hexiagon_Announcement";
    public static final String ORDER_BY_JPQL = " ORDER BY announcement.title ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Hexiagon_Announcement.title ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.zenixia.plugins.hexiagon.model.Announcement"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.zenixia.plugins.hexiagon.model.Announcement"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.zenixia.plugins.hexiagon.model.Announcement"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static long CURRENCYID_COLUMN_BITMASK = 2L;
    public static long GROUPID_COLUMN_BITMASK = 4L;
    public static long STATUS_COLUMN_BITMASK = 8L;
    public static long TYPEID_COLUMN_BITMASK = 16L;
    public static long UUID_COLUMN_BITMASK = 32L;
    public static long TITLE_COLUMN_BITMASK = 64L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.zenixia.plugins.hexiagon.model.Announcement"));
    private static ClassLoader _classLoader = Announcement.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Announcement.class
        };
    private String _uuid;
    private String _originalUuid;
    private long _announcementId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _userId;
    private String _userUuid;
    private long _typeId;
    private long _originalTypeId;
    private boolean _setOriginalTypeId;
    private long _folderId;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private long _currencyId;
    private long _originalCurrencyId;
    private boolean _setOriginalCurrencyId;
    private String _title;
    private String _titleCurrentLanguageId;
    private String _emailAddress;
    private String _phoneNumber;
    private long _price;
    private String _content;
    private String _contentCurrentLanguageId;
    private int _status;
    private int _originalStatus;
    private boolean _setOriginalStatus;
    private long _statusByUserId;
    private String _statusByUserUuid;
    private String _statusByUserName;
    private Date _statusDate;
    private long _countryId;
    private long _regionId;
    private long _columnBitmask;
    private Announcement _escapedModel;

    public AnnouncementModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Announcement toModel(AnnouncementSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Announcement model = new AnnouncementImpl();

        model.setUuid(soapModel.getUuid());
        model.setAnnouncementId(soapModel.getAnnouncementId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setGroupId(soapModel.getGroupId());
        model.setUserId(soapModel.getUserId());
        model.setTypeId(soapModel.getTypeId());
        model.setFolderId(soapModel.getFolderId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setCurrencyId(soapModel.getCurrencyId());
        model.setTitle(soapModel.getTitle());
        model.setEmailAddress(soapModel.getEmailAddress());
        model.setPhoneNumber(soapModel.getPhoneNumber());
        model.setPrice(soapModel.getPrice());
        model.setContent(soapModel.getContent());
        model.setStatus(soapModel.getStatus());
        model.setStatusByUserId(soapModel.getStatusByUserId());
        model.setStatusByUserName(soapModel.getStatusByUserName());
        model.setStatusDate(soapModel.getStatusDate());
        model.setCountryId(soapModel.getCountryId());
        model.setRegionId(soapModel.getRegionId());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Announcement> toModels(AnnouncementSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Announcement> models = new ArrayList<Announcement>(soapModels.length);

        for (AnnouncementSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _announcementId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setAnnouncementId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _announcementId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Announcement.class;
    }

    @Override
    public String getModelClassName() {
        return Announcement.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("announcementId", getAnnouncementId());
        attributes.put("companyId", getCompanyId());
        attributes.put("groupId", getGroupId());
        attributes.put("userId", getUserId());
        attributes.put("typeId", getTypeId());
        attributes.put("folderId", getFolderId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("currencyId", getCurrencyId());
        attributes.put("title", getTitle());
        attributes.put("emailAddress", getEmailAddress());
        attributes.put("phoneNumber", getPhoneNumber());
        attributes.put("price", getPrice());
        attributes.put("content", getContent());
        attributes.put("status", getStatus());
        attributes.put("statusByUserId", getStatusByUserId());
        attributes.put("statusByUserName", getStatusByUserName());
        attributes.put("statusDate", getStatusDate());
        attributes.put("countryId", getCountryId());
        attributes.put("regionId", getRegionId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long announcementId = (Long) attributes.get("announcementId");

        if (announcementId != null) {
            setAnnouncementId(announcementId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        Long typeId = (Long) attributes.get("typeId");

        if (typeId != null) {
            setTypeId(typeId);
        }

        Long folderId = (Long) attributes.get("folderId");

        if (folderId != null) {
            setFolderId(folderId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        Long currencyId = (Long) attributes.get("currencyId");

        if (currencyId != null) {
            setCurrencyId(currencyId);
        }

        String title = (String) attributes.get("title");

        if (title != null) {
            setTitle(title);
        }

        String emailAddress = (String) attributes.get("emailAddress");

        if (emailAddress != null) {
            setEmailAddress(emailAddress);
        }

        String phoneNumber = (String) attributes.get("phoneNumber");

        if (phoneNumber != null) {
            setPhoneNumber(phoneNumber);
        }

        Long price = (Long) attributes.get("price");

        if (price != null) {
            setPrice(price);
        }

        String content = (String) attributes.get("content");

        if (content != null) {
            setContent(content);
        }

        Integer status = (Integer) attributes.get("status");

        if (status != null) {
            setStatus(status);
        }

        Long statusByUserId = (Long) attributes.get("statusByUserId");

        if (statusByUserId != null) {
            setStatusByUserId(statusByUserId);
        }

        String statusByUserName = (String) attributes.get("statusByUserName");

        if (statusByUserName != null) {
            setStatusByUserName(statusByUserName);
        }

        Date statusDate = (Date) attributes.get("statusDate");

        if (statusDate != null) {
            setStatusDate(statusDate);
        }

        Long countryId = (Long) attributes.get("countryId");

        if (countryId != null) {
            setCountryId(countryId);
        }

        Long regionId = (Long) attributes.get("regionId");

        if (regionId != null) {
            setRegionId(regionId);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getAnnouncementId() {
        return _announcementId;
    }

    @Override
    public void setAnnouncementId(long announcementId) {
        _announcementId = announcementId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public long getTypeId() {
        return _typeId;
    }

    @Override
    public void setTypeId(long typeId) {
        _columnBitmask |= TYPEID_COLUMN_BITMASK;

        if (!_setOriginalTypeId) {
            _setOriginalTypeId = true;

            _originalTypeId = _typeId;
        }

        _typeId = typeId;
    }

    public long getOriginalTypeId() {
        return _originalTypeId;
    }

    @JSON
    @Override
    public long getFolderId() {
        return _folderId;
    }

    @Override
    public void setFolderId(long folderId) {
        _folderId = folderId;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public long getCurrencyId() {
        return _currencyId;
    }

    @Override
    public void setCurrencyId(long currencyId) {
        _columnBitmask |= CURRENCYID_COLUMN_BITMASK;

        if (!_setOriginalCurrencyId) {
            _setOriginalCurrencyId = true;

            _originalCurrencyId = _currencyId;
        }

        _currencyId = currencyId;
    }

    public long getOriginalCurrencyId() {
        return _originalCurrencyId;
    }

    @JSON
    @Override
    public String getTitle() {
        if (_title == null) {
            return StringPool.BLANK;
        } else {
            return _title;
        }
    }

    @Override
    public String getTitle(Locale locale) {
        String languageId = LocaleUtil.toLanguageId(locale);

        return getTitle(languageId);
    }

    @Override
    public String getTitle(Locale locale, boolean useDefault) {
        String languageId = LocaleUtil.toLanguageId(locale);

        return getTitle(languageId, useDefault);
    }

    @Override
    public String getTitle(String languageId) {
        return LocalizationUtil.getLocalization(getTitle(), languageId);
    }

    @Override
    public String getTitle(String languageId, boolean useDefault) {
        return LocalizationUtil.getLocalization(getTitle(), languageId,
            useDefault);
    }

    @Override
    public String getTitleCurrentLanguageId() {
        return _titleCurrentLanguageId;
    }

    @JSON
    @Override
    public String getTitleCurrentValue() {
        Locale locale = getLocale(_titleCurrentLanguageId);

        return getTitle(locale);
    }

    @Override
    public Map<Locale, String> getTitleMap() {
        return LocalizationUtil.getLocalizationMap(getTitle());
    }

    @Override
    public void setTitle(String title) {
        _columnBitmask = -1L;

        _title = title;
    }

    @Override
    public void setTitle(String title, Locale locale) {
        setTitle(title, locale, LocaleUtil.getSiteDefault());
    }

    @Override
    public void setTitle(String title, Locale locale, Locale defaultLocale) {
        String languageId = LocaleUtil.toLanguageId(locale);
        String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

        if (Validator.isNotNull(title)) {
            setTitle(LocalizationUtil.updateLocalization(getTitle(), "Title",
                    title, languageId, defaultLanguageId));
        } else {
            setTitle(LocalizationUtil.removeLocalization(getTitle(), "Title",
                    languageId));
        }
    }

    @Override
    public void setTitleCurrentLanguageId(String languageId) {
        _titleCurrentLanguageId = languageId;
    }

    @Override
    public void setTitleMap(Map<Locale, String> titleMap) {
        setTitleMap(titleMap, LocaleUtil.getSiteDefault());
    }

    @Override
    public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale) {
        if (titleMap == null) {
            return;
        }

        setTitle(LocalizationUtil.updateLocalization(titleMap, getTitle(),
                "Title", LocaleUtil.toLanguageId(defaultLocale)));
    }

    @JSON
    @Override
    public String getEmailAddress() {
        if (_emailAddress == null) {
            return StringPool.BLANK;
        } else {
            return _emailAddress;
        }
    }

    @Override
    public void setEmailAddress(String emailAddress) {
        _emailAddress = emailAddress;
    }

    @JSON
    @Override
    public String getPhoneNumber() {
        if (_phoneNumber == null) {
            return StringPool.BLANK;
        } else {
            return _phoneNumber;
        }
    }

    @Override
    public void setPhoneNumber(String phoneNumber) {
        _phoneNumber = phoneNumber;
    }

    @JSON
    @Override
    public long getPrice() {
        return _price;
    }

    @Override
    public void setPrice(long price) {
        _price = price;
    }

    @JSON
    @Override
    public String getContent() {
        if (_content == null) {
            return StringPool.BLANK;
        } else {
            return _content;
        }
    }

    @Override
    public String getContent(Locale locale) {
        String languageId = LocaleUtil.toLanguageId(locale);

        return getContent(languageId);
    }

    @Override
    public String getContent(Locale locale, boolean useDefault) {
        String languageId = LocaleUtil.toLanguageId(locale);

        return getContent(languageId, useDefault);
    }

    @Override
    public String getContent(String languageId) {
        return LocalizationUtil.getLocalization(getContent(), languageId);
    }

    @Override
    public String getContent(String languageId, boolean useDefault) {
        return LocalizationUtil.getLocalization(getContent(), languageId,
            useDefault);
    }

    @Override
    public String getContentCurrentLanguageId() {
        return _contentCurrentLanguageId;
    }

    @JSON
    @Override
    public String getContentCurrentValue() {
        Locale locale = getLocale(_contentCurrentLanguageId);

        return getContent(locale);
    }

    @Override
    public Map<Locale, String> getContentMap() {
        return LocalizationUtil.getLocalizationMap(getContent());
    }

    @Override
    public void setContent(String content) {
        _content = content;
    }

    @Override
    public void setContent(String content, Locale locale) {
        setContent(content, locale, LocaleUtil.getSiteDefault());
    }

    @Override
    public void setContent(String content, Locale locale, Locale defaultLocale) {
        String languageId = LocaleUtil.toLanguageId(locale);
        String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

        if (Validator.isNotNull(content)) {
            setContent(LocalizationUtil.updateLocalization(getContent(),
                    "Content", content, languageId, defaultLanguageId));
        } else {
            setContent(LocalizationUtil.removeLocalization(getContent(),
                    "Content", languageId));
        }
    }

    @Override
    public void setContentCurrentLanguageId(String languageId) {
        _contentCurrentLanguageId = languageId;
    }

    @Override
    public void setContentMap(Map<Locale, String> contentMap) {
        setContentMap(contentMap, LocaleUtil.getSiteDefault());
    }

    @Override
    public void setContentMap(Map<Locale, String> contentMap,
        Locale defaultLocale) {
        if (contentMap == null) {
            return;
        }

        setContent(LocalizationUtil.updateLocalization(contentMap,
                getContent(), "Content", LocaleUtil.toLanguageId(defaultLocale)));
    }

    @JSON
    @Override
    public int getStatus() {
        return _status;
    }

    @Override
    public void setStatus(int status) {
        _columnBitmask |= STATUS_COLUMN_BITMASK;

        if (!_setOriginalStatus) {
            _setOriginalStatus = true;

            _originalStatus = _status;
        }

        _status = status;
    }

    public int getOriginalStatus() {
        return _originalStatus;
    }

    @JSON
    @Override
    public long getStatusByUserId() {
        return _statusByUserId;
    }

    @Override
    public void setStatusByUserId(long statusByUserId) {
        _statusByUserId = statusByUserId;
    }

    @Override
    public String getStatusByUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getStatusByUserId(), "uuid",
            _statusByUserUuid);
    }

    @Override
    public void setStatusByUserUuid(String statusByUserUuid) {
        _statusByUserUuid = statusByUserUuid;
    }

    @JSON
    @Override
    public String getStatusByUserName() {
        if (_statusByUserName == null) {
            return StringPool.BLANK;
        } else {
            return _statusByUserName;
        }
    }

    @Override
    public void setStatusByUserName(String statusByUserName) {
        _statusByUserName = statusByUserName;
    }

    @JSON
    @Override
    public Date getStatusDate() {
        return _statusDate;
    }

    @Override
    public void setStatusDate(Date statusDate) {
        _statusDate = statusDate;
    }

    @JSON
    @Override
    public long getCountryId() {
        return _countryId;
    }

    @Override
    public void setCountryId(long countryId) {
        _countryId = countryId;
    }

    @JSON
    @Override
    public long getRegionId() {
        return _regionId;
    }

    @Override
    public void setRegionId(long regionId) {
        _regionId = regionId;
    }

    @Override
    public StagedModelType getStagedModelType() {
        return new StagedModelType(PortalUtil.getClassNameId(
                Announcement.class.getName()));
    }

    /**
     * @deprecated As of 6.1.0, replaced by {@link #isApproved}
     */
    @Override
    public boolean getApproved() {
        return isApproved();
    }

    @Override
    public boolean isApproved() {
        if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isDenied() {
        if (getStatus() == WorkflowConstants.STATUS_DENIED) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isDraft() {
        if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isExpired() {
        if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isInactive() {
        if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isIncomplete() {
        if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isPending() {
        if (getStatus() == WorkflowConstants.STATUS_PENDING) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isScheduled() {
        if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
            return true;
        } else {
            return false;
        }
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Announcement.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public String[] getAvailableLanguageIds() {
        Set<String> availableLanguageIds = new TreeSet<String>();

        Map<Locale, String> titleMap = getTitleMap();

        for (Map.Entry<Locale, String> entry : titleMap.entrySet()) {
            Locale locale = entry.getKey();
            String value = entry.getValue();

            if (Validator.isNotNull(value)) {
                availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
            }
        }

        Map<Locale, String> contentMap = getContentMap();

        for (Map.Entry<Locale, String> entry : contentMap.entrySet()) {
            Locale locale = entry.getKey();
            String value = entry.getValue();

            if (Validator.isNotNull(value)) {
                availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
            }
        }

        return availableLanguageIds.toArray(new String[availableLanguageIds.size()]);
    }

    @Override
    public String getDefaultLanguageId() {
        String xml = getTitle();

        if (xml == null) {
            return StringPool.BLANK;
        }

        return LocalizationUtil.getDefaultLanguageId(xml);
    }

    @Override
    public void prepareLocalizedFieldsForImport() throws LocaleException {
        prepareLocalizedFieldsForImport(null);
    }

    @Override
    @SuppressWarnings("unused")
    public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
        throws LocaleException {
        Locale defaultLocale = LocaleUtil.getDefault();

        String modelDefaultLanguageId = getDefaultLanguageId();

        String title = getTitle(defaultLocale);

        if (Validator.isNull(title)) {
            setTitle(getTitle(modelDefaultLanguageId), defaultLocale);
        } else {
            setTitle(getTitle(defaultLocale), defaultLocale, defaultLocale);
        }

        String content = getContent(defaultLocale);

        if (Validator.isNull(content)) {
            setContent(getContent(modelDefaultLanguageId), defaultLocale);
        } else {
            setContent(getContent(defaultLocale), defaultLocale, defaultLocale);
        }
    }

    @Override
    public Announcement toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Announcement) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        AnnouncementImpl announcementImpl = new AnnouncementImpl();

        announcementImpl.setUuid(getUuid());
        announcementImpl.setAnnouncementId(getAnnouncementId());
        announcementImpl.setCompanyId(getCompanyId());
        announcementImpl.setGroupId(getGroupId());
        announcementImpl.setUserId(getUserId());
        announcementImpl.setTypeId(getTypeId());
        announcementImpl.setFolderId(getFolderId());
        announcementImpl.setUserName(getUserName());
        announcementImpl.setCreateDate(getCreateDate());
        announcementImpl.setModifiedDate(getModifiedDate());
        announcementImpl.setCurrencyId(getCurrencyId());
        announcementImpl.setTitle(getTitle());
        announcementImpl.setEmailAddress(getEmailAddress());
        announcementImpl.setPhoneNumber(getPhoneNumber());
        announcementImpl.setPrice(getPrice());
        announcementImpl.setContent(getContent());
        announcementImpl.setStatus(getStatus());
        announcementImpl.setStatusByUserId(getStatusByUserId());
        announcementImpl.setStatusByUserName(getStatusByUserName());
        announcementImpl.setStatusDate(getStatusDate());
        announcementImpl.setCountryId(getCountryId());
        announcementImpl.setRegionId(getRegionId());

        announcementImpl.resetOriginalValues();

        return announcementImpl;
    }

    @Override
    public int compareTo(Announcement announcement) {
        int value = 0;

        value = getTitle().compareTo(announcement.getTitle());

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Announcement)) {
            return false;
        }

        Announcement announcement = (Announcement) obj;

        long primaryKey = announcement.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        AnnouncementModelImpl announcementModelImpl = this;

        announcementModelImpl._originalUuid = announcementModelImpl._uuid;

        announcementModelImpl._originalCompanyId = announcementModelImpl._companyId;

        announcementModelImpl._setOriginalCompanyId = false;

        announcementModelImpl._originalGroupId = announcementModelImpl._groupId;

        announcementModelImpl._setOriginalGroupId = false;

        announcementModelImpl._originalTypeId = announcementModelImpl._typeId;

        announcementModelImpl._setOriginalTypeId = false;

        announcementModelImpl._originalCurrencyId = announcementModelImpl._currencyId;

        announcementModelImpl._setOriginalCurrencyId = false;

        announcementModelImpl._originalStatus = announcementModelImpl._status;

        announcementModelImpl._setOriginalStatus = false;

        announcementModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Announcement> toCacheModel() {
        AnnouncementCacheModel announcementCacheModel = new AnnouncementCacheModel();

        announcementCacheModel.uuid = getUuid();

        String uuid = announcementCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            announcementCacheModel.uuid = null;
        }

        announcementCacheModel.announcementId = getAnnouncementId();

        announcementCacheModel.companyId = getCompanyId();

        announcementCacheModel.groupId = getGroupId();

        announcementCacheModel.userId = getUserId();

        announcementCacheModel.typeId = getTypeId();

        announcementCacheModel.folderId = getFolderId();

        announcementCacheModel.userName = getUserName();

        String userName = announcementCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            announcementCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            announcementCacheModel.createDate = createDate.getTime();
        } else {
            announcementCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            announcementCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            announcementCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        announcementCacheModel.currencyId = getCurrencyId();

        announcementCacheModel.title = getTitle();

        String title = announcementCacheModel.title;

        if ((title != null) && (title.length() == 0)) {
            announcementCacheModel.title = null;
        }

        announcementCacheModel.emailAddress = getEmailAddress();

        String emailAddress = announcementCacheModel.emailAddress;

        if ((emailAddress != null) && (emailAddress.length() == 0)) {
            announcementCacheModel.emailAddress = null;
        }

        announcementCacheModel.phoneNumber = getPhoneNumber();

        String phoneNumber = announcementCacheModel.phoneNumber;

        if ((phoneNumber != null) && (phoneNumber.length() == 0)) {
            announcementCacheModel.phoneNumber = null;
        }

        announcementCacheModel.price = getPrice();

        announcementCacheModel.content = getContent();

        String content = announcementCacheModel.content;

        if ((content != null) && (content.length() == 0)) {
            announcementCacheModel.content = null;
        }

        announcementCacheModel.status = getStatus();

        announcementCacheModel.statusByUserId = getStatusByUserId();

        announcementCacheModel.statusByUserName = getStatusByUserName();

        String statusByUserName = announcementCacheModel.statusByUserName;

        if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
            announcementCacheModel.statusByUserName = null;
        }

        Date statusDate = getStatusDate();

        if (statusDate != null) {
            announcementCacheModel.statusDate = statusDate.getTime();
        } else {
            announcementCacheModel.statusDate = Long.MIN_VALUE;
        }

        announcementCacheModel.countryId = getCountryId();

        announcementCacheModel.regionId = getRegionId();

        return announcementCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(45);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", announcementId=");
        sb.append(getAnnouncementId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", typeId=");
        sb.append(getTypeId());
        sb.append(", folderId=");
        sb.append(getFolderId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", currencyId=");
        sb.append(getCurrencyId());
        sb.append(", title=");
        sb.append(getTitle());
        sb.append(", emailAddress=");
        sb.append(getEmailAddress());
        sb.append(", phoneNumber=");
        sb.append(getPhoneNumber());
        sb.append(", price=");
        sb.append(getPrice());
        sb.append(", content=");
        sb.append(getContent());
        sb.append(", status=");
        sb.append(getStatus());
        sb.append(", statusByUserId=");
        sb.append(getStatusByUserId());
        sb.append(", statusByUserName=");
        sb.append(getStatusByUserName());
        sb.append(", statusDate=");
        sb.append(getStatusDate());
        sb.append(", countryId=");
        sb.append(getCountryId());
        sb.append(", regionId=");
        sb.append(getRegionId());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(70);

        sb.append("<model><model-name>");
        sb.append("com.zenixia.plugins.hexiagon.model.Announcement");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>announcementId</column-name><column-value><![CDATA[");
        sb.append(getAnnouncementId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>typeId</column-name><column-value><![CDATA[");
        sb.append(getTypeId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>folderId</column-name><column-value><![CDATA[");
        sb.append(getFolderId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>currencyId</column-name><column-value><![CDATA[");
        sb.append(getCurrencyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>title</column-name><column-value><![CDATA[");
        sb.append(getTitle());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>emailAddress</column-name><column-value><![CDATA[");
        sb.append(getEmailAddress());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>phoneNumber</column-name><column-value><![CDATA[");
        sb.append(getPhoneNumber());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>price</column-name><column-value><![CDATA[");
        sb.append(getPrice());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>content</column-name><column-value><![CDATA[");
        sb.append(getContent());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>status</column-name><column-value><![CDATA[");
        sb.append(getStatus());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
        sb.append(getStatusByUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
        sb.append(getStatusByUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>statusDate</column-name><column-value><![CDATA[");
        sb.append(getStatusDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>countryId</column-name><column-value><![CDATA[");
        sb.append(getCountryId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>regionId</column-name><column-value><![CDATA[");
        sb.append(getRegionId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
