package com.zenixia.plugins.hexiagon.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.zenixia.plugins.hexiagon.model.Currency;
import com.zenixia.plugins.hexiagon.service.CurrencyLocalServiceUtil;

/**
 * The extended model base implementation for the Currency service. Represents a row in the &quot;Hexiagon_Currency&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CurrencyImpl}.
 * </p>
 *
 * @author guillaumelenoir
 * @see CurrencyImpl
 * @see com.zenixia.plugins.hexiagon.model.Currency
 * @generated
 */
public abstract class CurrencyBaseImpl extends CurrencyModelImpl
    implements Currency {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a currency model instance should use the {@link Currency} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CurrencyLocalServiceUtil.addCurrency(this);
        } else {
            CurrencyLocalServiceUtil.updateCurrency(this);
        }
    }
}
