package com.zenixia.plugins.hexiagon.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.zenixia.plugins.hexiagon.model.Favorite;
import com.zenixia.plugins.hexiagon.service.FavoriteLocalServiceUtil;

/**
 * The extended model base implementation for the Favorite service. Represents a row in the &quot;Hexiagon_Favorite&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FavoriteImpl}.
 * </p>
 *
 * @author guillaumelenoir
 * @see FavoriteImpl
 * @see com.zenixia.plugins.hexiagon.model.Favorite
 * @generated
 */
public abstract class FavoriteBaseImpl extends FavoriteModelImpl
    implements Favorite {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a favorite model instance should use the {@link Favorite} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            FavoriteLocalServiceUtil.addFavorite(this);
        } else {
            FavoriteLocalServiceUtil.updateFavorite(this);
        }
    }
}
