package com.gleo.plugins.hexiagon.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the Type service. Represents a row in the &quot;Hexiagon_Type&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.gleo.plugins.hexiagon.model.impl.TypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.gleo.plugins.hexiagon.model.impl.TypeImpl}.
 * </p>
 *
 * @author guillaumelenoir
 * @see Type
 * @see com.gleo.plugins.hexiagon.model.impl.TypeImpl
 * @see com.gleo.plugins.hexiagon.model.impl.TypeModelImpl
 * @generated
 */
public interface TypeModel extends BaseModel<Type> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a type model instance should use the {@link Type} interface instead.
     */

    /**
     * Returns the primary key of this type.
     *
     * @return the primary key of this type
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this type.
     *
     * @param primaryKey the primary key of this type
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the type ID of this type.
     *
     * @return the type ID of this type
     */
    public long getTypeId();

    /**
     * Sets the type ID of this type.
     *
     * @param typeId the type ID of this type
     */
    public void setTypeId(long typeId);

    /**
     * Returns the name of this type.
     *
     * @return the name of this type
     */
    public String getName();

    /**
     * Returns the localized name of this type in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param locale the locale of the language
     * @return the localized name of this type
     */
    @AutoEscape
    public String getName(Locale locale);

    /**
     * Returns the localized name of this type in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param locale the local of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized name of this type. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
     */
    @AutoEscape
    public String getName(Locale locale, boolean useDefault);

    /**
     * Returns the localized name of this type in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @return the localized name of this type
     */
    @AutoEscape
    public String getName(String languageId);

    /**
     * Returns the localized name of this type in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized name of this type
     */
    @AutoEscape
    public String getName(String languageId, boolean useDefault);

    @AutoEscape
    public String getNameCurrentLanguageId();

    @AutoEscape
    public String getNameCurrentValue();

    /**
     * Returns a map of the locales and localized names of this type.
     *
     * @return the locales and localized names of this type
     */
    public Map<Locale, String> getNameMap();

    /**
     * Sets the name of this type.
     *
     * @param name the name of this type
     */
    public void setName(String name);

    /**
     * Sets the localized name of this type in the language.
     *
     * @param name the localized name of this type
     * @param locale the locale of the language
     */
    public void setName(String name, Locale locale);

    /**
     * Sets the localized name of this type in the language, and sets the default locale.
     *
     * @param name the localized name of this type
     * @param locale the locale of the language
     * @param defaultLocale the default locale
     */
    public void setName(String name, Locale locale, Locale defaultLocale);

    public void setNameCurrentLanguageId(String languageId);

    /**
     * Sets the localized names of this type from the map of locales and localized names.
     *
     * @param nameMap the locales and localized names of this type
     */
    public void setNameMap(Map<Locale, String> nameMap);

    /**
     * Sets the localized names of this type from the map of locales and localized names, and sets the default locale.
     *
     * @param nameMap the locales and localized names of this type
     * @param defaultLocale the default locale
     */
    public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

    /**
     * Returns the group ID of this type.
     *
     * @return the group ID of this type
     */
    public long getGroupId();

    /**
     * Sets the group ID of this type.
     *
     * @param groupId the group ID of this type
     */
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this type.
     *
     * @return the company ID of this type
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this type.
     *
     * @param companyId the company ID of this type
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the order of this type.
     *
     * @return the order of this type
     */
    public int getOrder();

    /**
     * Sets the order of this type.
     *
     * @param order the order of this type
     */
    public void setOrder(int order);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public String[] getAvailableLanguageIds();

    public String getDefaultLanguageId();

    public void prepareLocalizedFieldsForImport() throws LocaleException;

    public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
        throws LocaleException;

    @Override
    public Object clone();

    @Override
    public int compareTo(Type type);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Type> toCacheModel();

    @Override
    public Type toEscapedModel();

    @Override
    public Type toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
