package com.gleo.plugins.hexiagon.model.impl;

import com.gleo.plugins.hexiagon.model.AnnouncementImage;
import com.gleo.plugins.hexiagon.service.AnnouncementImageLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the AnnouncementImage service. Represents a row in the &quot;Hexiagon_AnnouncementImage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnnouncementImageImpl}.
 * </p>
 *
 * @author guillaumelenoir
 * @see AnnouncementImageImpl
 * @see com.gleo.plugins.hexiagon.model.AnnouncementImage
 * @generated
 */
public abstract class AnnouncementImageBaseImpl
    extends AnnouncementImageModelImpl implements AnnouncementImage {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a announcement image model instance should use the {@link AnnouncementImage} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AnnouncementImageLocalServiceUtil.addAnnouncementImage(this);
        } else {
            AnnouncementImageLocalServiceUtil.updateAnnouncementImage(this);
        }
    }
}
